Todo list
alvarorf/todo-list pull request #1
Opened 2021-04-01 23:12 UTC by alvarorf

Features:
- All the page is inside a single index.html file, and the tabs are rendered dynamically with Javascript.
- ES6 syntax is used, whenever possible.
- The project is modularized, with different files for each section of the page.
- Webpack is used to compile javascript, css and images.
- Users can create projects, add todos, remove todos.
- Localstorage is used as a database.

2021-04-02 06:36 UTC, peterrobert requested changes
### CHANGES REQUIRED ♻️ 🛑 
Hello @alvarorf  and @Mohamed-js, very nice work 👏🏿 . Great work with the design 👏🏿 . I also love the way your commit messages are consistent with capitalized sentences and are written in the right tense.

However, there are a few changes to be made to your project kindly check below ⬇️ 

- [ ] Kindly add an edit functionality for your to-do list. This is a hard requirement for this project. ⬇️  As you can see in the third point, your application should be able to edit a to-do item.

![ui_requirement](https://user-images.githubusercontent.com/32361963/113388272-98a10900-9396-11eb-84dd-b22ae8777ff9.png)

- [ ] Below you will see that you need to add some configuration for your web pack. I have  described the issue in more details below ⬇️ 


### if you have any question, kindly reach me via slack @peterrobert

### HAPPY CODING 💻

2021-04-02 06:36 UTC, peterrobert commented on package.json
> +  },
Great work adding web pack configuration 👏🏿 . However, let's improve them.

Kindly add all the necessary commands. This will ensure your project is well configured. Kindly check below for a hint for better web pack configuration. ⬇️ 
![scripts_requirement](https://user-images.githubusercontent.com/32361963/113387368-de5cd200-9394-11eb-9ee5-328076776f08.png)

Hint: Kindly configure your web pack like below:

```
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },

```

2021-04-02 06:36 UTC, peterrobert commented on src/helpers.js
> +};
### [OPTIONAL]

- [ ] Kindly add validations to your project form and your to-do list form. This will ensure that a user can not create an empty project or an empty to-do list.

2021-04-02 20:26 UTC, trekab requested changes
#### Changes Required! :recycle: 
Hi team! Unfortunately, I am unable to review most of your changes because the app returns an error when I try to run it. The image below shows the error and the output I see on my end.

![Screenshot](https://github.com/trekab/images/blob/master/img/todoListApp.png?raw=true)

Try to fix that existing bug. It would also be nice if you:

- [ ] __[Optional]__ Make your setup instructions in the `README.md` file more descriptive. They are not clear enough e.g. `Open the page`, which page should one open after the `npm install` command?
- [ ] __[Optional]__ Deploy your app and share the link to the deployed version in the `README.md` file. This would be helpful in cases where one fails to run your project locally.

__Please make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

2021-04-03 21:24 UTC, Torres-ssf approved these changes
### PR Approved :+1: 
Hi team :hand: 
Awesome job on this project. 
Also, a great job implementing the requested changes.

- [ ] Check my comment below before merging the branch

Happy coding :computer: 
**Sérgio Torres**

2021-04-03 21:24 UTC, Torres-ssf commented on package.json
> +    "start": "webpack-dev-server --mode development --open",
- [ ] We need to change the start script in order to use it. This way does not work anymore. Let's update this before merging the branch.
```JS
"start": "webpack serve --mode development --open",
```

2021-04-05 20:13 UTC, merged